apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enketo.fullname" . }}
  labels:
    {{- include "enketo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "enketo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.global.enketoSecrets | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "enketo.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enketo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/
              port: http
          readinessProbe:
            httpGet:
              path: /-/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOMAIN
              value: "{{ .Values.config.centralDomain }}"
            - name: SUPPORT_EMAIL
              value: "{{ .Values.config.supportEmail }}"
            - name: HTTPS_PORT
              value: "{{ .Values.config.httpsPort }}"
            - name: REDIS_MAIN_HOST
              value: '{{ .Values.config.redisMainHost | default (printf "%s-enketo-redis-main" .Release.Name) }}'
            - name: REDIS_MAIN_PORT
              value: "{{ .Values.config.redisMainPort }}"
            - name: REDIS_CACHE_HOST
              value: '{{ .Values.config.redisCacheHost | default (printf "%s-enketo-redis-cache" .Release.Name) }}'
            - name: REDIS_CACHE_PORT
              value: "{{ .Values.config.redisCachePort }}"
            {{- if .Values.config.debug }}
            - name: DEBUG
              value: "enketo*"
            {{- end }}
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secrets"
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.global.enketoSecretName }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
