apiVersion: v1
kind: Secret
metadata:
  name: {{ include "publish-mdm.fullname" . }}
  labels:
    {{- include "publish-mdm.labels" . | nindent 4 }}
{{- with .Values.environmentVariables }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
type: Opaque
