apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.enketoSecretName }}
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
data:
  enketo-secret: "{{ .Values.global.enketoSecrets.enketoSecret | b64enc }}"
  enketo-less-secret: "{{ .Values.global.enketoSecrets.enketoLessSecret | b64enc }}"
  enketo-api-key: "{{ .Values.global.enketoSecrets.enketoApiKey | b64enc }}"
