# Default values for odk-central.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  centralDomain: www.example.com
  enketoSecretName: central-enketo-secrets
  enketoSecrets: {}
    # Set to 64-character random string
    # enketoSecret: ""
    # Set to 32-character random string
    # enketoLessSecret: ""
    # Set to 128-character random string
    # enketoApiKey: ""

enketo-redis-main:
  enabled: true

  replicas: 1

  # use emptyDir to avoid tying pods to nodes during development
  # (not sure what this is used for, might be okay long-term too)
  persistentVolume:
    enabled: false
  emptyDir:
    sizeLimit: 500Mi

enketo-redis-cache:
  enabled: true

  replicas: 1

  # use emptyDir to avoid tying pods to nodes during development
  # (maybe okay long-term since this is just a cache?)
  persistentVolume:
    enabled: false
  emptyDir:
    sizeLimit: 500Mi

enketo:
  enabled: true

frontend:
  enabled: true
  environmentVariables:
    CERTBOT_EMAIL: ""
    DOMAIN: ""
    SENTRY_KEY: 3cf75f54983e473da6bd07daddf0d2ee
    SENTRY_ORG_SUBDOMAIN: o130137
    SENTRY_PROJECT: "1298632"
    SSL_TYPE: upstream

backend:
  enabled: true
  environmentVariables:
    DB_HOST: postgres14
    DB_NAME: odk
    DB_PASSWORD: odk
    DB_SSL: "null"
    DB_USER: odk
    DOMAIN: ""
    EMAIL_FROM: no-reply@
    EMAIL_HOST: mail
    EMAIL_IGNORE_TLS: "true"
    EMAIL_PASSWORD: ""
    EMAIL_PORT: "25"
    EMAIL_SECURE: "false"
    EMAIL_USER: ""
    HTTPS_PORT: "443"
    NODE_OPTIONS: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_ENABLED: "false"
    OIDC_ISSUER_URL: ""
    SENTRY_KEY: 3cf75f54983e473da6bd07daddf0d2ee
    SENTRY_ORG_SUBDOMAIN: o130137
    SENTRY_PROJECT: "1298632"
    SYSADMIN_EMAIL: ""

pyxform:
  enabled: true
